stages:
  - lintcode
  - install
  - build
  - push
  - clean

job1:
  stage: lintcode
  script:
    - echo `lintcode`
    
job2:
  stage: install
  script:
    - echo `install`


job3:
  stage: build
  script:
    - echo `build`


job4:
  stage: push
  script:
    - echo `push`

job5:
  stage: clean
  script:
    - echo `clean`
